#ifndef MAX17262_REGISTERS_H_
#define MAX17262_REGISTERS_H_

#define STATUS_REG 0x0
#define DESIGN_CAP_REG 0x18
#define ICHG_TERM_REG 0x1E
#define VEMPTY_REG 0x3A
#define FSTAT_REG 0x3D
#define MODEL_CFG_REG 0xDB
#define HIBER_CFG_REG 0xBA
#define SOFTWK_CFG_REG 0x60

#endif
